<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Computing in R 2023 - Untangling Data with Tidyverse: Data wranggling in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Statistical Computing in R 2023</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-lectures" role="button" data-bs-toggle="dropdown" aria-expanded="false">Lectures</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-lectures">    
        <li>
    <a class="dropdown-item" href="./introduction_R.html">
 <span class="dropdown-text">Introduction</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_wranggling.html">
 <span class="dropdown-text">Data Wranggling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_viz.html">
 <span class="dropdown-text">Data Visualisation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./inferential_stats.html">
 <span class="dropdown-text">Inferential Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression.html">
 <span class="dropdown-text">Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tutorials" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tutorials</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-tutorials">    
        <li>
    <a class="dropdown-item" href="./data_wranggling_tutorial.html">
 <span class="dropdown-text">Data Wranggling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_viz_tutorial.html">
 <span class="dropdown-text">Data Visualisation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./inferential_stats_tutorial.html">
 <span class="dropdown-text">Inferential Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression_tutorial.html">
 <span class="dropdown-text">Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-solutions" role="button" data-bs-toggle="dropdown" aria-expanded="false">Solutions</a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-solutions">    
        <li>
    <a class="dropdown-item" href="./data_wranggling_solutions.html">
 <span class="dropdown-text">Data Wranggling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_viz_solutions.html">
 <span class="dropdown-text">Data Visualisation</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./inferential_stats_solutions.html">
 <span class="dropdown-text">Inferential Statistics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./regression_solutions.html">
 <span class="dropdown-text">Regression</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/vivekjason"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/vivekjason87"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="./index.xml"><i class="bi bi-rss" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-tidyverse" id="toc-the-tidyverse" class="nav-link active" data-scroll-target="#the-tidyverse">The “Tidyverse”</a>
  <ul class="collapse">
  <li><a href="#data-frames" id="toc-data-frames" class="nav-link" data-scroll-target="#data-frames">Data Frames</a></li>
  <li><a href="#tibbles" id="toc-tibbles" class="nav-link" data-scroll-target="#tibbles">Tibbles</a>
  <ul class="collapse">
  <li><a href="#how-tibbles-differ-from-data.frame" id="toc-how-tibbles-differ-from-data.frame" class="nav-link" data-scroll-target="#how-tibbles-differ-from-data.frame">How tibbles differ from <code>data.frame</code></a></li>
  <li><a href="#converting-to-data.frame-or-tibble" id="toc-converting-to-data.frame-or-tibble" class="nav-link" data-scroll-target="#converting-to-data.frame-or-tibble">Converting to data.frame or tibble</a></li>
  <li><a href="#calling-in-some-data" id="toc-calling-in-some-data" class="nav-link" data-scroll-target="#calling-in-some-data">Calling in some data</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#the-dplyr-package" id="toc-the-dplyr-package" class="nav-link" data-scroll-target="#the-dplyr-package">The <code>dplyr</code> Package</a>
  <ul class="collapse">
  <li><a href="#dplyr-grammar" id="toc-dplyr-grammar" class="nav-link" data-scroll-target="#dplyr-grammar"><code>dplyr</code> grammar</a></li>
  <li><a href="#select" id="toc-select" class="nav-link" data-scroll-target="#select"><code>select()</code></a></li>
  <li><a href="#filter" id="toc-filter" class="nav-link" data-scroll-target="#filter"><code>filter()</code></a></li>
  <li><a href="#arrange" id="toc-arrange" class="nav-link" data-scroll-target="#arrange"><code>arrange()</code></a></li>
  <li><a href="#rename" id="toc-rename" class="nav-link" data-scroll-target="#rename"><code>rename()</code></a></li>
  <li><a href="#mutate" id="toc-mutate" class="nav-link" data-scroll-target="#mutate"><code>mutate()</code></a></li>
  <li><a href="#group_by" id="toc-group_by" class="nav-link" data-scroll-target="#group_by"><code>group_by()</code></a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"><code>%&gt;%</code></a></li>
  <li><a href="#slice_" id="toc-slice_" class="nav-link" data-scroll-target="#slice_"><code>slice_*()</code></a></li>
  <li><a href="#pivoting-in-r" id="toc-pivoting-in-r" class="nav-link" data-scroll-target="#pivoting-in-r">Pivoting in R</a>
  <ul class="collapse">
  <li><a href="#pivot_wider" id="toc-pivot_wider" class="nav-link" data-scroll-target="#pivot_wider"><code>pivot_wider()</code></a></li>
  <li><a href="#pivot_longer" id="toc-pivot_longer" class="nav-link" data-scroll-target="#pivot_longer"><code>pivot_longer()</code></a></li>
  <li><a href="#separate-and-unite" id="toc-separate-and-unite" class="nav-link" data-scroll-target="#separate-and-unite"><code>separate()</code> and <code>unite()</code></a></li>
  </ul></li>
  <li><a href="#mutating-joins" id="toc-mutating-joins" class="nav-link" data-scroll-target="#mutating-joins">Mutating joins</a>
  <ul class="collapse">
  <li><a href="#left-join" id="toc-left-join" class="nav-link" data-scroll-target="#left-join">Left Join</a></li>
  <li><a href="#inner-join" id="toc-inner-join" class="nav-link" data-scroll-target="#inner-join">Inner Join</a></li>
  <li><a href="#right-join" id="toc-right-join" class="nav-link" data-scroll-target="#right-join">Right Join</a></li>
  </ul></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements">Acknowledgements</a></li>
  <li><a href="#additional-resources" id="toc-additional-resources" class="nav-link" data-scroll-target="#additional-resources">Additional Resources</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Untangling Data with Tidyverse: Data wranggling in R</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p><img src="./images/banner.png" class="img-fluid"></p>
<p>Data cleaning is arguably the most crucial step in the data analysis pipeline because it directly impacts the accuracy and reliability of insights drawn from the data.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Garbage in, garbage out, as the saying goes.
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div>
<p>Without thoroughly cleaning the data, we might be working with incorrect, inconsistent, or irrelevant information, leading to potentially faulty conclusions. Data cleaning ensures the data is correctly formatted, accurate, complete, and ready for analysis. It involves dealing with missing values, removing duplicates, correcting inconsistencies, and handling outliers. Only after a rigorous data cleaning process can we trust that our analysis or model will give us meaningful, actionable insights.</p>
<p>Thus, while it can be a time-consuming process, skipping or skimping on data cleaning can lead to wasting even more time and resources downstream, as we try to interpret misleading results or troubleshoot models that aren’t performing as expected.</p>
<p><img src="./images/1_Xhm9c9qDfXa3ZCQjiOvm_w.jpg" class="img-fluid"></p>
<section id="the-tidyverse" class="level1">
<h1>The “Tidyverse”</h1>
<p>There are a number of R packages that take advantage of the tidy data form and can be used to do interesting things with data. Many (but not all) of these packages are written by Hadley Wickham and <strong>the collection of packages is often referred to as the “tidyverse”</strong> because of their <strong>dependence on and presumption of tidy data</strong>.</p>
<p>A subset of the “Tidyverse” packages include:</p>
<ul>
<li><p><a href="https://cran.r-project.org/package=ggplot2">ggplot2</a>: a plotting system based on the grammar of graphics</p></li>
<li><p><a href="https://cran.r-project.org/package=magrittr%22">magrittr</a>: defines the <code>%&gt;%</code> operator for chaining functions together in a series of operations on data</p></li>
<li><p><a href="https://cran.r-project.org/package=dplyr">dplyr</a>: a suite of (fast) functions for working with data frames</p></li>
<li><p><a href="https://cran.r-project.org/package=tidyr">tidyr</a>: easily tidy data with <code>pivot_wider()</code> and <code>pivot_longer()</code> functions (also <code>separate()</code> and <code>unite()</code>)</p></li>
</ul>
<p>A complete list can be found here (<a href="https://www.tidyverse.org/packages" class="uri">https://www.tidyverse.org/packages</a>).</p>
<p>We can call in the tidyverse as mentioned in the introduction like this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dplyr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.2.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.2     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.0
✔ ggplot2   3.4.2     ✔ tibble    3.2.1
✔ lubridate 1.9.2     ✔ tidyr     1.3.0
✔ purrr     1.0.1     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
</div>
<section id="data-frames" class="level2">
<h2 class="anchored" data-anchor-id="data-frames">Data Frames</h2>
<p>The <strong>data frame</strong> (or <code>data.frame</code>) is a <strong>key data structure</strong> in statistics and in R.</p>
<p>The basic structure of a data frame is that there is <strong>one observation per row and each column represents a variable, a measure, feature, or characteristic of that observation</strong>.</p>
</section>
<section id="tibbles" class="level2">
<h2 class="anchored" data-anchor-id="tibbles">Tibbles</h2>
<p>Another type of data structure that we need to discuss is called the <strong>tibble</strong>! It’s best to think of tibbles as an updated and stylish version of the <code>data.frame</code>.</p>
<p>Before we go any further, tibbles <em>are</em> data frames, but they have some new bells and whistles to make your life easier.</p>
<section id="how-tibbles-differ-from-data.frame" class="level3">
<h3 class="anchored" data-anchor-id="how-tibbles-differ-from-data.frame">How tibbles differ from <code>data.frame</code></h3>
<ul>
<li><strong>Input type remains unchanged</strong> - <code>data.frame</code> is notorious for treating strings as factors; this will not happen with tibbles</li>
<li><strong>Variable names remain unchanged</strong> - In base R, creating <code>data.frames</code> will remove spaces from names, converting them to periods or add “x” before numeric column names. Creating tibbles will not change variable (column) names.</li>
<li><strong>There are no <code>row.names()</code> for a tibble</strong> - Tidy data requires that variables be stored in a consistent way, removing the need for row names.</li>
<li><strong>Tibbles print first ten rows and columns that fit on one screen</strong> - Printing a tibble to screen will never print the entire huge data frame out. By default, it just shows what fits to your screen.</li>
</ul>
</section>
<section id="converting-to-data.frame-or-tibble" class="level3">
<h3 class="anchored" data-anchor-id="converting-to-data.frame-or-tibble">Converting to data.frame or tibble</h3>
<p>Use the <code>as.data.frame()</code> or <code>as_tibble()</code></p>
</section>
<section id="calling-in-some-data" class="level3">
<h3 class="anchored" data-anchor-id="calling-in-some-data">Calling in some data</h3>
<p>For the purposes of this session lets utilise the Malaysian COVID-19 deaths linelinest maintained by the Ministry of Health on their <a href="https://github.com/MoH-Malaysia">Github page</a>. Codes for each column are as follows:</p>
<ol type="1">
<li><p><code>date</code>: yyyy-mm-dd format; date of death</p></li>
<li><p><code>date_announced</code>: date on which the death was announced to the public (i.e.&nbsp;registered in the public linelist)</p></li>
<li><p><code>date_positive</code>: date of positive sample</p></li>
<li><p><code>date_doseN</code>: date of the individual’s first/second/third dose (if any)</p></li>
<li><p><code>brandN</code>: <code>p</code> = Pfizer, <code>s</code> = Sinovac, <code>a</code> = AstraZeneca, <code>c</code> = Cansino, <code>m</code> = Moderna, <code>h</code> = Sinopharm, <code>j</code> = Janssen, <code>u</code> = unverified (pending sync with VMS)</p></li>
<li><p><code>state</code>: state of residence</p></li>
<li><p><code>age</code>: age as an integer; note that it is possible for age to be 0, denoting infants less than 6 months old</p></li>
<li><p><code>male</code>: binary variable with 1 denoting male and 0 denoting female</p></li>
<li><p><code>bid</code>: binary variable with 1 denoting brought-in-dead and 0 denoting an inpatient death</p></li>
<li><p><code>malaysian</code>: binary variable with 1 denoting Malaysian and 0 denoting non-Malaysian</p></li>
<li><p><code>comorb</code>: binary variable with 1 denoting that the individual has comorbidities and 0 denoting no comorbidities declared</p></li>
</ol>
<p>Lets call in the data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/linelist/linelist_deaths.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Check the data structure</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(c19_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   37152 obs. of  15 variables:
 $ date          : chr  "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_announced: chr  "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_positive : chr  "2020-03-12" "2020-03-15" "2020-03-11" "2020-03-13" ...
 $ date_dose1    : chr  "" "" "" "" ...
 $ date_dose2    : chr  "" "" "" "" ...
 $ date_dose3    : chr  "" "" "" "" ...
 $ brand1        : chr  "" "" "" "" ...
 $ brand2        : chr  "" "" "" "" ...
 $ brand3        : chr  "" "" "" "" ...
 $ state         : chr  "Johor" "Sarawak" "Sabah" "Melaka" ...
 $ age           : int  34 60 58 50 80 39 57 69 48 73 ...
 $ male          : int  1 1 1 1 0 0 1 1 1 1 ...
 $ bid           : int  0 0 0 0 1 0 0 0 0 0 ...
 $ malaysian     : int  1 1 1 1 1 1 1 1 1 1 ...
 $ comorb        : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(c19_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 37152    15</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="the-dplyr-package" class="level1">
<h1>The <code>dplyr</code> Package</h1>
<p>The <code>dplyr</code> package was developed by Posit (formely RStudio) and is <strong>an optimized and distilled</strong> version of the older <code>plyr</code> <strong>package for data manipulation or wrangling</strong>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/allisonhorst/stats-illustrations/raw/main/rstats-artwork/dplyr_wrangling.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Artwork by Allison Horst on the dplyr package</figcaption><p></p>
</figure>
</div>
<p>[<strong>Source</strong>: <a href="https://github.com/allisonhorst/stats-illustrations">Artwork by Allison Horst</a>]</p>
<p>The <code>dplyr</code> package does not provide any “new” functionality to R per se, in the sense that everything <code>dplyr</code> does could already be done with base R, but it <strong>greatly</strong> simplifies existing functionality in R.</p>
<p>One important contribution of the <code>dplyr</code> package is that it <strong>provides a “grammar” (in particular, verbs) for data manipulation and for operating on data frames</strong>.</p>
<p>With this grammar, you can sensibly communicate what it is that you are doing to a data frame that other people can understand (assuming they also know the grammar). This is useful because it <strong>provides an abstraction for data manipulation that previously did not exist</strong>.</p>
<p>Another useful contribution is that the <code>dplyr</code> functions are <strong>very</strong> fast, as many key operations are coded in C++.</p>
<section id="dplyr-grammar" class="level3">
<h3 class="anchored" data-anchor-id="dplyr-grammar"><code>dplyr</code> grammar</h3>
<p>Some of the key “verbs” provided by the <code>dplyr</code> package are</p>
<ul>
<li><p><code>select()</code>: return a subset of the columns of a data frame, using a flexible notation</p></li>
<li><p><code>filter()</code>: extract a subset of rows from a data frame based on logical conditions</p></li>
<li><p><code>arrange()</code>: reorder rows of a data frame</p></li>
<li><p><code>rename()</code>: rename variables in a data frame</p></li>
<li><p><code>mutate()</code>: add new variables/columns or transform existing variables</p></li>
<li><p><code>summarise()</code> / <code>summarize()</code>: generate summary statistics of different variables in the data frame, possibly within strata</p></li>
<li><p><code>%&gt;%</code>: the “pipe” operator is used to connect multiple verb actions together into a pipelineArtwork by</p></li>
</ul>
</section>
<section id="select" class="level3">
<h3 class="anchored" data-anchor-id="select"><code>select()</code></h3>
<p>Lets convert the COVID-19 deaths linelist into a tibble first</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(c19_df)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(c19_df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [37,152 × 15] (S3: tbl_df/tbl/data.frame)
 $ date          : chr [1:37152] "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_announced: chr [1:37152] "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_positive : chr [1:37152] "2020-03-12" "2020-03-15" "2020-03-11" "2020-03-13" ...
 $ date_dose1    : chr [1:37152] "" "" "" "" ...
 $ date_dose2    : chr [1:37152] "" "" "" "" ...
 $ date_dose3    : chr [1:37152] "" "" "" "" ...
 $ brand1        : chr [1:37152] "" "" "" "" ...
 $ brand2        : chr [1:37152] "" "" "" "" ...
 $ brand3        : chr [1:37152] "" "" "" "" ...
 $ state         : chr [1:37152] "Johor" "Sarawak" "Sabah" "Melaka" ...
 $ age           : int [1:37152] 34 60 58 50 80 39 57 69 48 73 ...
 $ male          : int [1:37152] 1 1 1 1 0 0 1 1 1 1 ...
 $ bid           : int [1:37152] 0 0 0 0 1 0 0 0 0 0 ...
 $ malaysian     : int [1:37152] 1 1 1 1 1 1 1 1 1 1 ...
 $ comorb        : int [1:37152] 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
<p>The <code>select()</code> function can be used to <strong>select columns of a data frame</strong> that you want to focus on.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we wanted to take the last 5 columns only. There are a few ways to do this.</p>
<p>We could for example use numerical indices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(c19_df)[<span class="dv">10</span><span class="sc">:</span><span class="dv">15</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "state"     "age"       "male"      "bid"       "malaysian" "comorb"   </code></pre>
</div>
</div>
<p>But we can also use the names directly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>subset <span class="ot">&lt;-</span> <span class="fu">select</span>(c19_df, state<span class="sc">:</span>comorb)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 6
  state     age  male   bid malaysian comorb
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;     &lt;int&gt;  &lt;int&gt;
1 Johor      34     1     0         1      1
2 Sarawak    60     1     0         1      1
3 Sabah      58     1     0         1      1
4 Melaka     50     1     0         1      1
5 Sarawak    80     0     1         1      1
6 Sarawak    39     0     0         1      1</code></pre>
</div>
</div>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>:</code> normally cannot be used with names or strings, but inside the <code>select()</code> function you can use it to specify a range of variable names.</p>
</div>
</div>
<p>You can also <strong>omit</strong> variables using the <code>select()</code> function by using the negative sign. With <code>select()</code> you can do</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(c19_df, <span class="sc">-</span>(state<span class="sc">:</span>comorb))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>select()</code> function also allows a special syntax that allows you to specify variable names based on patterns. So, for example, if you wanted to keep every variable that ends with a “2”, we could do</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>subset <span class="ot">&lt;-</span> <span class="fu">select</span>(c19_df, <span class="fu">ends_with</span>(<span class="fu">c</span>(<span class="st">"1"</span>, <span class="st">"2"</span>, <span class="st">"3"</span>)))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [37,152 × 6] (S3: tbl_df/tbl/data.frame)
 $ date_dose1: chr [1:37152] "" "" "" "" ...
 $ brand1    : chr [1:37152] "" "" "" "" ...
 $ date_dose2: chr [1:37152] "" "" "" "" ...
 $ brand2    : chr [1:37152] "" "" "" "" ...
 $ date_dose3: chr [1:37152] "" "" "" "" ...
 $ brand3    : chr [1:37152] "" "" "" "" ...</code></pre>
</div>
</div>
<p>Or if we wanted to keep every variable that starts with a “date”, we could do</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>subset <span class="ot">&lt;-</span> <span class="fu">select</span>(c19_df, <span class="fu">contains</span>(<span class="st">"date"</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(subset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [37,152 × 6] (S3: tbl_df/tbl/data.frame)
 $ date          : chr [1:37152] "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_announced: chr [1:37152] "2020-03-17" "2020-03-17" "2020-03-20" "2020-03-21" ...
 $ date_positive : chr [1:37152] "2020-03-12" "2020-03-15" "2020-03-11" "2020-03-13" ...
 $ date_dose1    : chr [1:37152] "" "" "" "" ...
 $ date_dose2    : chr [1:37152] "" "" "" "" ...
 $ date_dose3    : chr [1:37152] "" "" "" "" ...</code></pre>
</div>
</div>
<p>You can also use more general regular expressions if necessary. See the help page (<code>?select</code>) for more details.</p>
</section>
<section id="filter" class="level3">
<h3 class="anchored" data-anchor-id="filter"><code>filter()</code></h3>
<p>The <code>filter()</code> function is used to <strong>extract subsets of rows</strong> from a data frame. This function is similar to the existing <code>subset()</code> function in R but is quite a bit faster in my experience.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/allisonhorst/stats-illustrations/raw/main/rstats-artwork/dplyr_filter.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Artwork by Allison Horst on filter() function</figcaption><p></p>
</figure>
</div>
<p>[<strong>Source</strong>: <a href="https://github.com/allisonhorst/stats-illustrations">Artwork by Allison Horst</a>]</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we wanted to extract the rows of the <code>c19_df</code> data frame of deaths in individuals older than 60, we could do</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>c19_filter <span class="ot">&lt;-</span> <span class="fu">filter</span>(c19_df, age <span class="sc">&gt;</span> <span class="dv">59</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(c19_filter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [22,276 × 15] (S3: tbl_df/tbl/data.frame)
 $ date          : chr [1:22276] "2020-03-17" "2020-03-22" "2020-03-21" "2020-03-22" ...
 $ date_announced: chr [1:22276] "2020-03-17" "2020-03-22" "2020-03-21" "2020-03-22" ...
 $ date_positive : chr [1:22276] "2020-03-15" "2020-03-20" "2020-03-17" "2020-03-14" ...
 $ date_dose1    : chr [1:22276] "" "" "" "" ...
 $ date_dose2    : chr [1:22276] "" "" "" "" ...
 $ date_dose3    : chr [1:22276] "" "" "" "" ...
 $ brand1        : chr [1:22276] "" "" "" "" ...
 $ brand2        : chr [1:22276] "" "" "" "" ...
 $ brand3        : chr [1:22276] "" "" "" "" ...
 $ state         : chr [1:22276] "Sarawak" "Sarawak" "Kelantan" "Pulau Pinang" ...
 $ age           : int [1:22276] 60 80 69 73 70 70 70 75 66 68 ...
 $ male          : int [1:22276] 1 0 1 1 1 1 1 1 1 0 ...
 $ bid           : int [1:22276] 0 1 0 0 0 0 0 0 0 0 ...
 $ malaysian     : int [1:22276] 1 1 1 1 1 1 1 1 1 1 ...
 $ comorb        : int [1:22276] 1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
</div>
</div>
</div>
<p>You can see that there are now only 22276 rows in the data frame and the distribution of the <code>age</code> values is.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(c19_filter<span class="sc">$</span>age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   60.0    66.0    73.0    73.7    81.0   130.0 </code></pre>
</div>
</div>
<p>We can place an arbitrarily complex logical sequence inside of <code>filter()</code>, so we could for example extract the rows where age is greater than 60 and nationality (<code>malaysian</code>) is equal to 1</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>c19_filter <span class="ot">&lt;-</span> <span class="fu">filter</span>(c19_df, age <span class="sc">&lt;</span> <span class="dv">21</span> <span class="sc">&amp;</span> malaysian<span class="sc">==</span><span class="dv">1</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">select</span>(c19_filter, date, malaysian, age)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 221 × 3
   date       malaysian   age
   &lt;chr&gt;          &lt;int&gt; &lt;int&gt;
 1 2020-10-05         1     1
 2 2020-11-08         1     2
 3 2020-11-15         1     8
 4 2020-11-04         1    15
 5 2021-02-03         1     0
 6 2021-01-21         1    18
 7 2021-02-09         1    20
 8 2021-02-13         1     9
 9 2021-05-10         1    17
10 2021-04-04         1     3
# ℹ 211 more rows</code></pre>
</div>
</div>
<p>Now there are only 221 observations where both of those conditions are met.</p>
<p>Other logical operators you should be aware of include:</p>
<table class="table">
<colgroup>
<col style="width: 14%">
<col style="width: 35%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Operator</th>
<th style="text-align: right;">Meaning</th>
<th style="text-align: right;">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><code>==</code></td>
<td style="text-align: right;">Equals</td>
<td style="text-align: right;"><code>malaysian== 1</code></td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>!=</code></td>
<td style="text-align: right;">Does not equal</td>
<td style="text-align: right;"><code>malaysian!= 1</code></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>&gt;</code></td>
<td style="text-align: right;">Greater than</td>
<td style="text-align: right;"><code>age&gt; 60</code></td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>&gt;=</code></td>
<td style="text-align: right;">Greater than or equal to</td>
<td style="text-align: right;"><code>age&gt;= 60</code></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>&lt;</code></td>
<td style="text-align: right;">Less than</td>
<td style="text-align: right;"><code>age&lt; 60</code></td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>&lt;=</code></td>
<td style="text-align: right;">Less than or equal to</td>
<td style="text-align: right;"><code>age&lt;= 60</code></td>
</tr>
<tr class="odd">
<td style="text-align: right;"><code>%in%</code></td>
<td style="text-align: right;">Included in</td>
<td style="text-align: right;"><code>state %in% c("Selangor", "Johor")</code></td>
</tr>
<tr class="even">
<td style="text-align: right;"><code>is.na()</code></td>
<td style="text-align: right;">Is a missing value</td>
<td style="text-align: right;"><code>is.na(date_dose_2)</code></td>
</tr>
</tbody>
</table>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>If you are ever unsure of how to write a logical statement, but know how to write its opposite, you can use the <code>!</code> operator to negate the whole statement.</p>
<p>A common use of this is to identify observations with non-missing data (e.g., <code>!(is.na(date_dose_2))</code>).</p>
</div>
</div>
</section>
<section id="arrange" class="level3">
<h3 class="anchored" data-anchor-id="arrange"><code>arrange()</code></h3>
<p>The <code>arrange()</code> function is used to <strong>reorder rows</strong> of a data frame according to one of the variables/columns. Reordering rows of a data frame (while preserving corresponding order of other columns) is normally a pain to do in R. The <code>arrange()</code> function simplifies the process quite a bit.</p>
<p>Here we can order the rows of the data frame by date, so that the first row is the earliest (oldest) observation and the last row is the latest (most recent) observation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">arrange</span>(c19_df, date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can now check the first few rows</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">select</span>(c19_df, date, age), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  date         age
  &lt;chr&gt;      &lt;int&gt;
1 2020-03-17    34
2 2020-03-17    60
3 2020-03-20    58</code></pre>
</div>
</div>
<p>Columns can be arranged in descending order too by useing the special <code>desc()</code> operator.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">arrange</span>(c19_df, <span class="fu">desc</span>(date))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Looking at the first three and last three rows shows the dates in descending order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">select</span>(c19_df, date, age), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  date         age
  &lt;chr&gt;      &lt;int&gt;
1 2023-06-27    79
2 2023-06-26    83
3 2023-06-22    68</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(<span class="fu">select</span>(c19_df, date, age), <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  date         age
  &lt;chr&gt;      &lt;int&gt;
1 2020-03-20    58
2 2020-03-17    34
3 2020-03-17    60</code></pre>
</div>
</div>
</section>
<section id="rename" class="level3">
<h3 class="anchored" data-anchor-id="rename"><code>rename()</code></h3>
<p><strong>Renaming a variable</strong> in a data frame in R is surprisingly hard to do! The <code>rename()</code> function is designed to make this process easier.</p>
<p>Here you can see the names of the first six variables in the <code>c19_df</code> data frame.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(c19_df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  date       date_announced date_positive date_dose1   date_dose2   date_dose3  
  &lt;chr&gt;      &lt;chr&gt;          &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;        &lt;chr&gt;       
1 2023-06-27 2023-07-01     2023-06-26    ""           ""           ""          
2 2023-06-26 2023-07-01     2023-06-10    "2021-06-30" "2021-07-21" ""          
3 2023-06-22 2023-06-24     2023-06-19    "2021-06-15" "2021-07-06" "2022-01-06"</code></pre>
</div>
</div>
<p>These names are (arbitrarily again) unnecessarily long. Date doesn’t need to be repeated for each column name are no other columns that could potentially be confused with the first six. So we can modify cause we’re lazy to type long column names when analysing later on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">rename</span>(c19_df, <span class="at">death =</span> date,</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>                 <span class="at">announced =</span> date_announced,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                 <span class="at">positive =</span> date_positive,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dose1 =</span> date_dose1,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dose2 =</span> date_dose2,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">dose3 =</span> date_dose3)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(c19_df[, <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>], <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  death      announced  positive   dose1        dose2       
  &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;      &lt;chr&gt;        &lt;chr&gt;       
1 2023-06-27 2023-07-01 2023-06-26 ""           ""          
2 2023-06-26 2023-07-01 2023-06-10 "2021-06-30" "2021-07-21"
3 2023-06-22 2023-06-24 2023-06-19 "2021-06-15" "2021-07-06"</code></pre>
</div>
</div>
<p>The syntax inside the <code>rename()</code> function is to have the new name on the left-hand side of the <code>=</code> sign and the old name on the right-hand side.</p>
</section>
<section id="mutate" class="level3">
<h3 class="anchored" data-anchor-id="mutate"><code>mutate()</code></h3>
<p>The <code>mutate()</code> function exists to <strong>compute transformations of variables</strong> in a data frame. Often, you want to create new variables that are derived from existing variables and <code>mutate()</code> provides a clean interface for doing that.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/allisonhorst/stats-illustrations/raw/main/rstats-artwork/dplyr_mutate.png" class="img-fluid figure-img" style="width:80.0%"></p>
<p></p><figcaption class="figure-caption">Artwork by Allison Horst on mutate() function</figcaption><p></p>
</figure>
</div>
<p>[<strong>Source</strong>: <a href="https://github.com/allisonhorst/stats-illustrations">Artwork by Allison Horst</a>]</p>
<p>For example, with demographic data, we often want to <em>categorise data</em></p>
<p>Here, we create a <code>age_cat</code> variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(c19_df, <span class="at">age_cat=</span> <span class="fu">ifelse</span>(age<span class="sc">&lt;</span><span class="dv">20</span>, <span class="st">"&lt;19"</span>, </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>                                         <span class="fu">ifelse</span>(age<span class="sc">&gt;</span><span class="dv">59</span>, <span class="st">"&gt;60"</span>, <span class="st">"20-59"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>we can also <code>recode</code> category values within a variable, such as</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="ot">&lt;-</span> <span class="fu">mutate</span>(c19_df,  <span class="at">brand2 =</span> <span class="fu">recode</span>(brand2, </span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Pfizer"</span> <span class="ot">=</span> <span class="dv">0</span>, </span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Sinovac"</span> <span class="ot">=</span> <span class="dv">1</span>, </span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"AstraZeneca"</span> <span class="ot">=</span> <span class="dv">2</span>, </span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Moderna"</span> <span class="ot">=</span> <span class="dv">2</span>, </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Pending VMS sync"</span> <span class="ot">=</span> <span class="dv">2</span>, </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"Sinopharm"</span> <span class="ot">=</span> <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `brand2 = recode(...)`.
Caused by warning:
! Unreplaced values treated as NA as `.x` is not compatible.
Please specify replacements exhaustively or supply `.default`.</code></pre>
</div>
</div>
</section>
<section id="group_by" class="level3">
<h3 class="anchored" data-anchor-id="group_by"><code>group_by()</code></h3>
<p>The <code>group_by()</code> function is used to <strong>generate summary statistics</strong> from the data frame within strata defined by a variable.</p>
<p>For example, in this dataset, you might want to know what the number of deaths in each state is?</p>
<p><strong>In conjunction</strong> with the <code>group_by()</code> function, we often use the <code>summarise()</code> function</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong>general operation</strong> here is a combination of</p>
<ol type="1">
<li>Splitting a data frame into separate pieces defined by a variable or group of variables (<code>group_by()</code>)</li>
<li>Then, applying a summary function across those subsets (<code>summarise()</code>)</li>
</ol>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>We can create a separate data frame that splits the original data frame by state</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>state <span class="ot">&lt;-</span> <span class="fu">group_by</span>(c19_df, state)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can then compute summary statistics for each year in the data frame with the <code>summarise()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summarise</span>(state, <span class="at">age =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">age_median=</span> <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 16 × 3
   state               age age_median
   &lt;chr&gt;             &lt;dbl&gt;      &lt;dbl&gt;
 1 Johor              60.9       60.9
 2 Kedah              63.1       63.1
 3 Kelantan           66.7       66.7
 4 Melaka             62.2       62.2
 5 Negeri Sembilan    64.5       64.5
 6 Pahang             63.2       63.2
 7 Perak              66.9       66.9
 8 Perlis             68.1       68.1
 9 Pulau Pinang       66.0       66.0
10 Sabah              65.4       65.4
11 Sarawak            68.1       68.1
12 Selangor           59.4       59.4
13 Terengganu         64.9       64.9
14 W.P. Kuala Lumpur  61.7       61.7
15 W.P. Labuan        59.3       59.3
16 W.P. Putrajaya     64.7       64.7</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"><code>%&gt;%</code></h3>
<p>The pipeline operator <code>%&gt;%</code> is very handy for <strong>stringing together multiple <code>dplyr</code> functions in a sequence of operations</strong>.</p>
<p>Notice above that every time we wanted to apply more than one function, the sequence gets buried in a sequence of nested function calls that is difficult to read, i.e.&nbsp;This <strong>nesting is not a natural way</strong> to think about a sequence of operations.</p>
<p>The <code>%&gt;%</code> operator allows you to string operations in a left-to-right fashion, i.e</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<p>Take the example that we just did in the last section.</p>
<p>That can be done with the following sequence in a single R expression.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="sc">%&gt;%</span> </span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(state, age) <span class="sc">%&gt;%</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(age) <span class="sc">%&gt;%</span></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">age_cat =</span> <span class="fu">ifelse</span>(age<span class="sc">&lt;</span><span class="dv">20</span>, <span class="st">"&lt;19"</span>, </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">ifelse</span>(age<span class="sc">&gt;</span><span class="dv">59</span>, <span class="st">"&gt;60"</span>, <span class="st">"20-59"</span>))) <span class="sc">%&gt;%</span>   </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state, age_cat) <span class="sc">%&gt;%</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">age =</span> <span class="fu">mean</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">age_median=</span> <span class="fu">median</span>(age, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'state'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 46 × 4
# Groups:   state [16]
   state    age_cat   age age_median
   &lt;chr&gt;    &lt;chr&gt;   &lt;dbl&gt;      &lt;dbl&gt;
 1 Johor    20-59   45.8       45.8 
 2 Johor    &lt;19      8.62       8.62
 3 Johor    &gt;60     73.5       73.5 
 4 Kedah    20-59   46.9       46.9 
 5 Kedah    &lt;19      7.47       7.47
 6 Kedah    &gt;60     73.7       73.7 
 7 Kelantan 20-59   47.7       47.7 
 8 Kelantan &lt;19     14.4       14.4 
 9 Kelantan &gt;60     74.1       74.1 
10 Melaka   20-59   46.0       46.0 
# ℹ 36 more rows</code></pre>
</div>
</div>
</div>
</div>
<p>This way we do not have to create a set of temporary variables along the way or create a massive nested sequence of function calls.</p>
</section>
<section id="slice_" class="level3">
<h3 class="anchored" data-anchor-id="slice_"><code>slice_*()</code></h3>
<p>The <code>slice_sample()</code> function of the <code>dplyr</code> package will allow you to see a <strong>sample of random rows</strong> in random order.</p>
<p>The number of rows to show is specified by the <code>n</code> argument.</p>
<ul>
<li>This can be useful if you <strong>do not want to print the entire tibble</strong>, but you want to get a greater sense of the values.</li>
<li>This is a <strong>good option for data analysis reports</strong>, where printing the entire tibble would not be appropriate if the tibble is quite large.</li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Example
</div>
</div>
<div class="callout-body-container callout-body">
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_sample</span>(c19_df, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 16
   death   announced positive dose1 dose2 dose3 brand1 brand2 brand3 state   age
   &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
 1 2021-0… 2021-09-… 2021-08… ""    ""    ""    ""         NA ""     Kedah    58
 2 2021-0… 2021-08-… 2021-08… ""    ""    ""    ""         NA ""     Johor    63
 3 2022-0… 2022-03-… 2022-03… ""    ""    ""    ""         NA ""     Nege…    91
 4 2020-0… 2020-09-… 2020-09… ""    ""    ""    ""         NA ""     Sabah    57
 5 2022-0… 2022-04-… 2022-03… "202… "202… ""    "Pfiz…      0 ""     Johor    76
 6 2021-0… 2021-05-… 2021-05… ""    ""    ""    ""         NA ""     Johor    58
 7 2022-0… 2022-03-… 2022-03… ""    ""    ""    ""         NA ""     Kela…    75
 8 2021-0… 2021-08-… 2021-08… "202… ""    ""    "Pfiz…     NA ""     Mela…    47
 9 2021-0… 2021-09-… 2021-08… ""    ""    ""    ""         NA ""     Sela…    55
10 2022-0… 2022-02-… 2022-02… ""    ""    ""    ""         NA ""     Sela…    96
# ℹ 5 more variables: male &lt;int&gt;, bid &lt;int&gt;, malaysian &lt;int&gt;, comorb &lt;int&gt;,
#   age_cat &lt;chr&gt;</code></pre>
</div>
</div>
</div>
</div>
<p>You can also use <code>slice_head()</code> or <code>slice_tail()</code> to take a look at the top rows or bottom rows of your tibble. Again the number of rows can be specified with the <code>n</code> argument.</p>
<p>This will show the first 5 rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_head</span>(c19_df, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 16
  death    announced positive dose1 dose2 dose3 brand1 brand2 brand3 state   age
  &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
1 2023-06… 2023-07-… 2023-06… ""    ""    ""    ""         NA ""     Perak    79
2 2023-06… 2023-07-… 2023-06… "202… "202… ""    "Sino…      1 ""     Kedah    83
3 2023-06… 2023-06-… 2023-06… "202… "202… "202… "Pfiz…      0 "Pfiz… Tere…    68
4 2023-06… 2023-06-… 2023-06… "202… "202… "202… "Sino…      1 "Pfiz… Perak    75
5 2023-06… 2023-06-… 2023-06… ""    ""    ""    ""         NA ""     Pula…    82
# ℹ 5 more variables: male &lt;int&gt;, bid &lt;int&gt;, malaysian &lt;int&gt;, comorb &lt;int&gt;,
#   age_cat &lt;chr&gt;</code></pre>
</div>
</div>
<p>This will show the last 5 rows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slice_tail</span>(c19_df, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 16
  death    announced positive dose1 dose2 dose3 brand1 brand2 brand3 state   age
  &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;    &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;
1 2020-03… 2020-03-… 2020-03… ""    ""    ""    ""         NA ""     W.P.…    57
2 2020-03… 2020-03-… 2020-03… ""    ""    ""    ""         NA ""     Kela…    69
3 2020-03… 2020-03-… 2020-03… ""    ""    ""    ""         NA ""     Sabah    58
4 2020-03… 2020-03-… 2020-03… ""    ""    ""    ""         NA ""     Johor    34
5 2020-03… 2020-03-… 2020-03… ""    ""    ""    ""         NA ""     Sara…    60
# ℹ 5 more variables: male &lt;int&gt;, bid &lt;int&gt;, malaysian &lt;int&gt;, comorb &lt;int&gt;,
#   age_cat &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="pivoting-in-r" class="level2">
<h2 class="anchored" data-anchor-id="pivoting-in-r">Pivoting in R</h2>
<p>The <code>tidyr</code> package includes functions to transfer a data frame between <em>long</em> and <em>wide</em>.</p>
<ul>
<li><strong>Wide format</strong> data tends to have different attributes or variables describing an observation placed in separate columns.</li>
<li><strong>Long format</strong> data tends to have different attributes encoded as levels of a single variable, followed by another column that contains values of the observation at those different levels.</li>
</ul>
<p>Lets create a sample set based on the deaths dataset focussing only on <code>brand2</code> uptake over time.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: There was 1 warning in `mutate()`.
ℹ In argument: `across(where(is.character), na_if, "")`.
Caused by warning:
! The `...` argument of `across()` is deprecated as of dplyr 1.1.0.
Supply arguments directly to `.fns` through an anonymous function instead.

  # Previously
  across(a:b, mean, na.rm = TRUE)

  # Now
  across(a:b, \(x) mean(x, na.rm = TRUE))</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'date'. You can override using the
`.groups` argument.</code></pre>
</div>
</div>
<section id="pivot_wider" class="level3">
<h3 class="anchored" data-anchor-id="pivot_wider"><code>pivot_wider()</code></h3>
<p>The <code>pivot_wider()</code> function is less commonly needed to tidy data as compared to its sister <code>pivot_longer</code>. It can, however, be useful for creating summary tables. As out sample dataset is already in long form- for the sake of this example we will <code>pivot_wider</code> first.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>dose2_df <span class="ot">&lt;-</span> dose2_df <span class="sc">%&gt;%</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols=</span><span class="st">"date"</span>,</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">names_from =</span> <span class="st">"brand2"</span>,</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> <span class="st">"count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tippy-tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>You use the <code>kable()</code> function in <code>dplyr</code> to make nicer looking html tables</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>dose2_df <span class="sc">%&gt;%</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate_all</span>(<span class="sc">~</span><span class="fu">replace_na</span>(., <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="at">format=</span><span class="st">"html"</span>, <span class="at">caption =</span> <span class="st">"Vaccinations among COVID-19 fatalities by Brand"</span>) <span class="sc">%&gt;%</span> kableExtra<span class="sc">::</span><span class="fu">kable_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`mutate_all()` ignored the following grouping variables:
• Column `date`
ℹ Use `mutate_at(df, vars(-group_cols()), myoperation)` to silence the message.</code></pre>
</div>
<div class="cell-output-display">

<table class=" lightable-minimal" style="font-family: &quot;Trebuchet MS&quot;, verdana, sans-serif; margin-left: auto; margin-right: auto;">
<caption>Vaccinations among COVID-19 fatalities by Brand</caption>
 <thead>
  <tr>
   <th style="text-align:left;"> date </th>
   <th style="text-align:right;"> unvaccinated </th>
   <th style="text-align:right;"> Pfizer </th>
   <th style="text-align:right;"> Sinovac </th>
   <th style="text-align:right;"> Pending VMS sync </th>
   <th style="text-align:right;"> AstraZeneca </th>
   <th style="text-align:right;"> Moderna </th>
   <th style="text-align:right;"> Sinopharm </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> 2020-03-17 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-20 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-21 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-22 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-23 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-24 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-25 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-26 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-27 </td>
   <td style="text-align:right;"> 2 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> 2020-03-28 </td>
   <td style="text-align:right;"> 6 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 0 </td>
  </tr>
</tbody>
</table>

</div>
</div>
</div>
</div>
</section>
<section id="pivot_longer" class="level3">
<h3 class="anchored" data-anchor-id="pivot_longer"><code>pivot_longer()</code></h3>
<p>Even if your data is in a tidy format, <code>pivot_longer()</code> is useful for pulling data together to take advantage of faceting, or plotting separate plots based on a grouping variable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>dose2_df <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>date, </span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">names_to =</span> <span class="st">"brand2"</span>,</span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">"count"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7,028 × 3
# Groups:   date [1,004]
   date       brand2           count
   &lt;chr&gt;      &lt;chr&gt;            &lt;int&gt;
 1 2020-03-17 unvaccinated         2
 2 2020-03-17 Pfizer              NA
 3 2020-03-17 Sinovac             NA
 4 2020-03-17 Pending VMS sync    NA
 5 2020-03-17 AstraZeneca         NA
 6 2020-03-17 Moderna             NA
 7 2020-03-17 Sinopharm           NA
 8 2020-03-20 unvaccinated         1
 9 2020-03-20 Pfizer              NA
10 2020-03-20 Sinovac             NA
# ℹ 7,018 more rows</code></pre>
</div>
</div>
</section>
<section id="separate-and-unite" class="level3">
<h3 class="anchored" data-anchor-id="separate-and-unite"><code>separate()</code> and <code>unite()</code></h3>
<p>The same <code>tidyr</code> package also contains two useful functions:</p>
<ul>
<li><code>unite()</code>: combine contents of two or more columns into a single column</li>
<li><code>separate()</code>: separate contents of a column into two or more columns</li>
</ul>
<p>First, we combine the first three columns into one new column using <code>unite()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(brand1, brand2, brand3) <span class="sc">%&gt;%</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(<span class="at">col=</span><span class="st">"profile"</span>, </span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>        brand1<span class="sc">:</span>brand3, </span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">sep=</span><span class="st">"_"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  profile
37143                                  __
37144                                  __
37145              Sinovac_Sinovac_Pfizer
37146                      Pfizer_Pfizer_
37147                                  __
37148                Pfizer_Pfizer_Pfizer
37149                Pfizer_Pfizer_Pfizer
37150 AstraZeneca_AstraZeneca_AstraZeneca
37151                                  __
37152                    Sinovac_Sinovac_</code></pre>
</div>
</div>
<p>Next, we show how to separate the columns into three separate columns using <code>separate()</code> using the <code>col</code>, <code>into</code> and <code>sep</code> arguments.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>c19_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(brand1, brand2, brand3) <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(<span class="at">col=</span><span class="st">"profile"</span>, </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>        brand1<span class="sc">:</span>brand3, </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">sep=</span><span class="st">"_"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(profile) <span class="sc">%&gt;%</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(<span class="at">col=</span><span class="st">"profile"</span>, </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">into=</span><span class="fu">c</span>(<span class="st">"brand1"</span>, <span class="st">"brand2"</span>, <span class="st">"brand3"</span>), </span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">sep=</span><span class="st">"_"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tail</span>(<span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           brand1      brand2      brand3
37143                                    
37144                                    
37145     Sinovac     Sinovac      Pfizer
37146      Pfizer      Pfizer            
37147                                    
37148      Pfizer      Pfizer      Pfizer
37149      Pfizer      Pfizer      Pfizer
37150 AstraZeneca AstraZeneca AstraZeneca
37151                                    
37152     Sinovac     Sinovac            </code></pre>
</div>
</div>
</section>
</section>
<section id="mutating-joins" class="level2">
<h2 class="anchored" data-anchor-id="mutating-joins">Mutating joins</h2>
<p>The <code>dplyr</code> package provides a set of <strong>functions for joining two data frames</strong> into a single data frame based on a set of key columns.</p>
<p>There are several functions in the <code>*_join()</code> family.</p>
<ul>
<li>These functions all merge together two data frames</li>
<li>They differ in how they handle observations that exist in one but not both data frames.</li>
</ul>
<p>Here, are the <strong>four functions from this family</strong> that you will likely use the most often:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">

<table>
 <thead>
  <tr>
   <th style="text-align:left;"> Function </th>
   <th style="text-align:left;"> What it includes in merged data frame </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> `left_join()` </td>
   <td style="text-align:left;"> Includes all observations in the left data frame, whether or not there is a match in the right data frame </td>
  </tr>
  <tr>
   <td style="text-align:left;"> `right_join()` </td>
   <td style="text-align:left;"> Includes all observations in the right data frame, whether or not there is a match in the left data frame </td>
  </tr>
  <tr>
   <td style="text-align:left;"> `inner_join()` </td>
   <td style="text-align:left;"> Includes only observations that are in both data frames </td>
  </tr>
  <tr>
   <td style="text-align:left;"> `full_join()` </td>
   <td style="text-align:left;"> Includes all observations from both data frames </td>
  </tr>
</tbody>
</table>

</div>
</div>
<p><img src="https://d33wubrfki0l68.cloudfront.net/aeab386461820b029b7e7606ccff1286f623bae1/ef0d4/diagrams/join-venn.png" class="img-fluid"></p>
<p>[<a href="https://r4ds.had.co.nz/relational-data#relational-data">Source from R for Data Science</a>]</p>
<p>Suppose we want to create a table that combines the information about COVID-19 deaths (<code>c19_df</code>) with the information about the expenditure (<code>hies_df</code>) at each state.</p>
<p>First lets take c19_df and aggregate it at the state level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>state_df <span class="ot">&lt;-</span> c19_df <span class="sc">%&gt;%</span> <span class="fu">select</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(state) <span class="sc">%&gt;%</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">deaths=</span><span class="fu">n</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets call in an external object to join</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>hies_df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/dosm-malaysia/data-open/main/datasets/economy/hies_2019.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets look at the data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(hies_df<span class="sc">$</span>area_type)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 district       dun parliment     state 
      160       600       222        16 </code></pre>
</div>
</div>
<section id="left-join" class="level3">
<h3 class="anchored" data-anchor-id="left-join">Left Join</h3>
<p>We can use the <code>left_join()</code> function to merge the <code>state_df</code> and <code>hies_df</code> datasets.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">left_join</span>(<span class="at">x =</span> state_df, <span class="at">y =</span> hies_df, <span class="at">by =</span> <span class="fu">join_by</span>(state<span class="sc">==</span>area))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 7
   state        deaths area_type income_mean expenditure_mean  gini poverty_rate
   &lt;chr&gt;         &lt;int&gt; &lt;chr&gt;           &lt;int&gt;            &lt;int&gt; &lt;dbl&gt;        &lt;dbl&gt;
 1 Johor          4740 state            8013             4793 0.366          3.9
 2 Kedah          2756 state            5522             3359 0.354          8.8
 3 Kelantan       1428 state            4874             3223 0.378         12.4
 4 Melaka         1213 state            7741             4955 0.383          3.9
 5 Negeri Semb…   1546 state            6707             4350 0.391          4.3
 6 Pahang         1037 state            5667             3652 0.33           4.3
 7 Perak          2164 state            5645             3564 0.377          7.3
 8 Perlis          199 state            5476             3468 0.334          3.9
 9 Perlis          199 district         5476             3468 0.334          3.9
10 Pulau Pinang   2085 state            7774             4630 0.359          1.9
11 Sabah          3211 state            5745             2792 0.397         19.5
12 Sarawak        1795 state            5959             3448 0.387          9  
13 Selangor      11024 state           10827             5830 0.393          1.2
14 Terengganu      905 state            6815             4336 0.335          6.1
15 W.P. Kuala …   2861 state           13257             6913 0.35           0.2
16 W.P. Kuala …   2861 district        13257             6913 0.35           0.2
17 W.P. Labuan     159 state            8319             4097 0.333          3.1
18 W.P. Labuan     159 district         8319             4097 0.333          3.1
19 W.P. Putraj…     29 state           12840             7980 0.361          0.4
20 W.P. Putraj…     29 district        12840             7980 0.361          0.4</code></pre>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>by</code> argument indicates the column (or columns) that the two tables have in common. One more than one joining variable an be used for this statement</p>
</div>
</div>
<p>Quite obviously the join should give you the total number of rows on the left side of your statement. Note in the above case there are 20 rows because there are four districts with the same name as states.</p>
</section>
<section id="inner-join" class="level3">
<h3 class="anchored" data-anchor-id="inner-join">Inner Join</h3>
<p>The <code>inner_join()</code> function only <strong>retains the rows of both tables</strong> that have corresponding values. Here we can see the difference.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inner_join</span>(<span class="at">x =</span> state_df, <span class="at">y =</span> hies_df, <span class="at">by =</span> <span class="fu">join_by</span>(state<span class="sc">==</span>area))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 20 × 7
   state        deaths area_type income_mean expenditure_mean  gini poverty_rate
   &lt;chr&gt;         &lt;int&gt; &lt;chr&gt;           &lt;int&gt;            &lt;int&gt; &lt;dbl&gt;        &lt;dbl&gt;
 1 Johor          4740 state            8013             4793 0.366          3.9
 2 Kedah          2756 state            5522             3359 0.354          8.8
 3 Kelantan       1428 state            4874             3223 0.378         12.4
 4 Melaka         1213 state            7741             4955 0.383          3.9
 5 Negeri Semb…   1546 state            6707             4350 0.391          4.3
 6 Pahang         1037 state            5667             3652 0.33           4.3
 7 Perak          2164 state            5645             3564 0.377          7.3
 8 Perlis          199 state            5476             3468 0.334          3.9
 9 Perlis          199 district         5476             3468 0.334          3.9
10 Pulau Pinang   2085 state            7774             4630 0.359          1.9
11 Sabah          3211 state            5745             2792 0.397         19.5
12 Sarawak        1795 state            5959             3448 0.387          9  
13 Selangor      11024 state           10827             5830 0.393          1.2
14 Terengganu      905 state            6815             4336 0.335          6.1
15 W.P. Kuala …   2861 state           13257             6913 0.35           0.2
16 W.P. Kuala …   2861 district        13257             6913 0.35           0.2
17 W.P. Labuan     159 state            8319             4097 0.333          3.1
18 W.P. Labuan     159 district         8319             4097 0.333          3.1
19 W.P. Putraj…     29 state           12840             7980 0.361          0.4
20 W.P. Putraj…     29 district        12840             7980 0.361          0.4</code></pre>
</div>
</div>
<p>Does <code>inner_join</code> give different results to <code>left_join</code> in the above example?</p>
</section>
<section id="right-join" class="level3">
<h3 class="anchored" data-anchor-id="right-join">Right Join</h3>
<p>The <code>right_join()</code> function is like the <code>left_join()</code> function except that it <strong>gives priority to the “right” hand argument</strong>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">right_join</span>(<span class="at">x =</span> state_df, <span class="at">y =</span> hies_df, <span class="at">by =</span> <span class="fu">join_by</span>(state<span class="sc">==</span>area))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 998 × 7
   state        deaths area_type income_mean expenditure_mean  gini poverty_rate
   &lt;chr&gt;         &lt;int&gt; &lt;chr&gt;           &lt;int&gt;            &lt;int&gt; &lt;dbl&gt;        &lt;dbl&gt;
 1 Johor          4740 state            8013             4793 0.366          3.9
 2 Kedah          2756 state            5522             3359 0.354          8.8
 3 Kelantan       1428 state            4874             3223 0.378         12.4
 4 Melaka         1213 state            7741             4955 0.383          3.9
 5 Negeri Semb…   1546 state            6707             4350 0.391          4.3
 6 Pahang         1037 state            5667             3652 0.33           4.3
 7 Perak          2164 state            5645             3564 0.377          7.3
 8 Perlis          199 state            5476             3468 0.334          3.9
 9 Perlis          199 district         5476             3468 0.334          3.9
10 Pulau Pinang   2085 state            7774             4630 0.359          1.9
# ℹ 988 more rows</code></pre>
</div>
</div>
<p>What about now?</p>
<p><img src="./images/normal.png" class="img-fluid"></p>
</section>
</section>
<section id="acknowledgements" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgements">Acknowledgements</h2>
<p>Material for this lecture was borrowed and adopted from</p>
<ul>
<li><p><a href="https://stephaniehicks.com/jhustatcomputing2022/" class="uri">https://stephaniehicks.com/jhustatcomputing2022/</a></p></li>
<li><p><a href="https://epirhandbook.com/en/index.html">The Epidemiologist R Handbook</a></p></li>
<li><p><a href="https://rafalab.github.io/dsbook" class="uri">https://rafalab.github.io/dsbook</a></p></li>
<li><p><a href="https://rmd4sci.njtierney.com" class="uri">https://rmd4sci.njtierney.com</a></p></li>
</ul>
</section>
<section id="additional-resources" class="level2">
<h2 class="anchored" data-anchor-id="additional-resources">Additional Resources</h2>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><a href="https://r4ds.had.co.nz/tibbles.html" class="uri">https://r4ds.had.co.nz/tibbles.html</a></li>
<li><a href="https://jhudatascience.org/tidyversecourse/wrangle-data.html#data-wrangling" class="uri">https://jhudatascience.org/tidyversecourse/wrangle-data.html#data-wrangling</a></li>
<li><a href="http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf">dplyr cheat sheet from RStudio</a></li>
</ul>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>